language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install nose pylint
script:
  - PYTHONPATH=src pylint --ignore=drivermsg_pb2.py amberclient.common || true
  - python setup.py test
